export type Color =  ""
                    |'pink'
                    |'cyan'
                    |'magenta'
                    |'orangered'
                    |'salmon'
                    |'lightseagreen'
                    |'burlywood'
                    |'white'
                    |'black'